// Mocks generated by Mockito 5.4.2 from annotations
// in currency_converter_demo/test/features/currencies/data/repositories/countries_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:currency_converter_demo/features/countries/data/datasources/remote/countries_remote_data_source.dart'
    as _i5;
import 'package:currency_converter_demo/features/countries/data/datasources/local/countries_local_data_source.dart'
    as _i2;
import 'package:currency_converter_demo/features/countries/data/models/country_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CountriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountriesLocalDataSource extends _i1.Mock
    implements _i2.CountriesLocalDataSource {
  @override
  _i3.Future<bool> get isEmptyLocalStorage => (super.noSuchMethod(
        Invocation.getter(#isEmptyLocalStorage),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<List<_i4.CountryModel>> getCachedCountries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedCountries,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.CountryModel>>.value(<_i4.CountryModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CountryModel>>.value(<_i4.CountryModel>[]),
      ) as _i3.Future<List<_i4.CountryModel>>);
  @override
  _i3.Future<bool> cacheCountries(List<_i4.CountryModel>? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCountries,
          [model],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [CountriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountriesRemoteDataSource extends _i1.Mock
    implements _i5.CountriesRemoteDataSource {
  @override
  _i3.Future<List<_i4.CountryModel>> getCountries() => (super.noSuchMethod(
        Invocation.method(
          #getCountries,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.CountryModel>>.value(<_i4.CountryModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CountryModel>>.value(<_i4.CountryModel>[]),
      ) as _i3.Future<List<_i4.CountryModel>>);
}
