// Mocks generated by Mockito 5.4.2 from annotations
// in currency_converter_demo/test/features/currencies/data/repositories/currencies_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:currency_converter_demo/features/currencies/data/datasources/currencies_local_data_source.dart'
    as _i2;
import 'package:currency_converter_demo/features/currencies/data/datasources/currencies_remote_data_source.dart'
    as _i5;
import 'package:currency_converter_demo/features/currencies/data/models/currency_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CurrenciesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrenciesLocalDataSource extends _i1.Mock
    implements _i2.CurrenciesLocalDataSource {
  @override
  _i3.Future<bool> get isEmptyLocalStorage => (super.noSuchMethod(
        Invocation.getter(#isEmptyLocalStorage),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<List<_i4.CurrencyModel>> getCachedCurrencies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedCurrencies,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
      ) as _i3.Future<List<_i4.CurrencyModel>>);
  @override
  _i3.Future<void> cacheCurrencies(List<_i4.CurrencyModel>? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCurrencies,
          [model],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [CurrenciesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrenciesRemoteDataSource extends _i1.Mock
    implements _i5.CurrenciesRemoteDataSource {
  @override
  _i3.Future<List<_i4.CurrencyModel>> getCurrencies() => (super.noSuchMethod(
        Invocation.method(
          #getCurrencies,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CurrencyModel>>.value(<_i4.CurrencyModel>[]),
      ) as _i3.Future<List<_i4.CurrencyModel>>);
}
